name: Node.js CI

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: |
          npm install
          npm install @lunapaint/png-codec
          npm install saver.db
      - name: Run main.js
        run: node main.js
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Dmi States"
          git pull origin main
          git add database.json
          git commit -m "Automatic dmi compile." -a || true
      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_PAT || secrets.GITHUB_TOKEN }}

     